Traceback (most recent call last):
  File "/home/archivebot-archives/archivebot-archives/code/update.py", line 72, in <module>
    raise ValueError('last-update file has an invalid format: does not contain exactly 4 lines')
ValueError: last-update file has an invalid format: does not contain exactly 4 lines
